language: node_js
os: linux
dist: trusty
node_js:
  - "8.9.4"
python: "3.6"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pyenv global 3.6
before_script:
  - "npm install"
sudo: false
notifications:
  email:
    - yelm-eng@microsoft.com
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
env:
  - PXT_ENV=production CXX=g++-4.8
